### ISSUE TITLE
I18N and L10N

### ISSUE THREAD

**Issue by mahony0** [rainlab/editable-plugin#15]
I'm developing E-commerce system with October and using this plugin. If you can add lang folder and make texts and inputs dynamic -takes only 5-10 mins.- this plugin will be very useful for me and others. I can help editing the plugin btw. Thanks.

**Comment by SaifurRahmanMohsin** [comment]
You can achieve this by using the translate plugin. And using this http://octobercms.com/plugin/rainlab-editable/not-working-with-translate fix

**Comment by mahony0** [comment]
I want this support for backend strings and dialogs, not for frontend files.

**Comment by SaifurRahmanMohsin** [comment]
I'm certain this plugin is targeted towards frontend. Besides the backend already has l10n and i18n capabilities. Check out the /modules/cms/lang folder. It has exactly what you described--even the folder name is 'lang'

**Comment by mahony0** [comment]
This plugin doesn't have I10n and I18n capabilities.. When you change /modules/cms/lang files, they will rolled-back to old version when you update the system.

https://github.com/rainlab/editable-plugin/blob/master/components/Editable.php#L19

Is this a compability for back-end users? I'm helping developers for making their plugin's language support dynamic and already I wrote my plugins with have full language supported. It's good thing for users of October CMS to have change their back-end even for all plugins. My client doesn't understand english well and like this, my system not being instutional.

**Comment by daftspunk** [comment]
Can someone submit a PR for this?

**Comment by vojtasvoboda** [comment]
PR sent in #26 and cs_CZ locale added in #27

**Comment by daftspunk** [comment]
Fixed by #26
