### ISSUE TITLE
data file mode txt wrapping text in p tags

### ISSUE THREAD

**Issue by geocine** [rainlab/editable-plugin#19]
I do not expect txt mode to wrap content in p tags. Why is this happening?

**Comment by madebyframe** [comment]
I'm having this issue as well.  There doesn't seem to be any way to reconfigure the redactor settings without breaking plugin updates etc.

**Comment by oryxgd** [comment]
Having the same problem as well, which is a kind of a deal breaker..

**Comment by lawelez** [comment]
suggesting

**Comment by faustoquaggia** [comment]
+1

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
