### ISSUE TITLE
Suggestion: the editor should display the actual md file when editing .md block, not the rendered html

### ISSUE THREAD

**Issue by johnchristopher** [rainlab/editable-plugin#20]
I am using Markdown in content block and the editable plug-in so I only have to edit chunks of text when I need to update information.

But having the md chunk rendered to html tags in the source code of the editor breaks that workflow and purpose since I have to type in a soup tag.

Could the editor load the md file without rendering it to html and leave it as it is ?

The current workaround I found is to convert .md files to .htm and use the wysywig editor but I don't want some users to mess with tags (even in the wysywig editor).

**Comment by BigSisl** [comment]
Would love this feature too :)

**Comment by daftspunk** [comment]
Sounds good, feel free to submit a PR. This plugin really was supposed to be a example of what's possible with October. Someone could really take this idea and run with it.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
