### ISSUE TITLE
Not working in partials (AJAX handler not found error)

### ISSUE THREAD

**Issue by lieszkol** [rainlab/editable-plugin#28]
If an editable is added to a partial, once the user tries to save changes to that content the browser throws an error: AJAX handler 'editable:onSave' was not found. 

Same editable works fine in a regular page.

Any suggestions would be much appreciated.

**Comment by lieszkol** [comment]
After doing my homework I read in the OctoverCMS docs on partials that "The following limitations should be noted: AJAX events are not registered and won't function as normal..."

So I'm guessing this is causing the problem. I was able to work around the issue by putting the component declaration for the editable in the page that contains the partial (instead of at the top of the partial file itself), and only putting the "{% content... %}" twig markup in the partial itself.

Anyways, this is an absolutely great plugin thanks so much for your work!

**Comment by JumpLink** [comment]
I think this issue should be fixed anyway
