### ISSUE TITLE
Please update to Froala :)

### ISSUE THREAD

**Issue by amdad** [rainlab/editable-plugin#29]

**Comment by JumpLink** [comment]
Or to [MediumEditor](https://yabwe.github.io/medium-editor/) ;)

**Comment by CptMeatball** [comment]
haven't we just updated to CK?

**Comment by daftspunk** [comment]
This plugin serves as an example of what is possible. It has lots of potential for many great features. We are hoping someone will submit Pull Requests to improve it, or fork it as an entirely new plugin.

**Comment by Alex360hd** [comment]
Checkout the [contenteditor ](https://octobercms.com/plugin/samuell-contenteditor)plugin that integrate contenttools. Fat better than editable plugin

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
