### ISSUE TITLE
Ability to use the media library

### ISSUE THREAD

**Issue by zietbukuel** [rainlab/editable-plugin#31]
Please add the ability to use the media library from the frontend of the site. Adding media elements is only possible using the backend which defeats the purpose of this plugin. I think this would be a really useful addition to the plugin. Thanks!

**Comment by benparsell** [comment]
Would love to see this as well. I'd love to help out building an addition if any support is needed.

**Comment by daftspunk** [comment]
This plugin serves as an example of what is possible. It has lots of potential for many great features. We are hoping someone will submit Pull Requests to improve it, or fork it as an entirely new plugin.

**Comment by Alex360hd** [comment]
Checkout the [contenteditor ](https://octobercms.com/plugin/samuell-contenteditor)plugin that integrate contenttools. Fat better than editable plugin

**Comment by daftspunk** [comment]
@Alex360hd Thanks, I've added a note to the editable plugin recommending to use this plugin instead:

http://octobercms.com/plugin/rainlab-editable

**Comment by zietbukuel** [comment]
Thanks @Alex360hd I'll check it out.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
