### ISSUE TITLE
JS error when interacting with the toolbar

### ISSUE THREAD

**Issue by jcardell** [rainlab/editable-plugin#32]
Hi everyone, someone had this error before? Everytime I interact with the redactor component, specially clicking the toolbar options this error appears.

I've added in the layout the {% framework %}, {% scripts %} and {% styles %} tags. What im doing wrong?

![ss 2016-09-20 at 04 12 54](https://cloud.githubusercontent.com/assets/6811411/18673788/5461eee2-7f4d-11e6-9cdb-d5e5221e0254.png)

![ss 2016-09-20 at 04 20 44](https://cloud.githubusercontent.com/assets/6811411/18674069/3dfb0390-7f4e-11e6-8bbc-d303f1916920.png)

![ss 2016-09-20 at 04 21 30](https://cloud.githubusercontent.com/assets/6811411/18674096/54af690a-7f4e-11e6-8ce3-158f8c9dc517.png)

**Comment by daftspunk** [comment]
What version of jQuery have you included with your site?

**Comment by jcardell** [comment]
I'm using version 3.1.0.

I didn't thought about that actually. I'll downgrade the jQuery version and let you know the results.

**Comment by jcardell** [comment]
@daftspunk I created a pull request #33 fixing the issue.

**Comment by daftspunk** [comment]
Cheers! Fixed by #33
