### ISSUE TITLE
Class name is not registered for the component "editable"

### ISSUE THREAD

**Issue by pixelhn** [rainlab/editable-plugin#36]
![screen shot 2017-01-10 at 3 13 00 p m](https://cloud.githubusercontent.com/assets/1638280/21824978/55bf35d6-d747-11e6-9a03-700c30366bb7.png)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by faheem121** [comment]
you have to register your component in plugin.php
public function registerComponents()
    {
  

        return [
              \Vagans\Vagan\Components\EMail::class       => 'EMail',
        ];
    }
